"""Agent service for managing agent instances"""
from typing import Optional, List

from app.agent.character import Character
from app.config import LLMSettings
from app.llm import LLM
from app.logger import logger
from app.prompt.character import ROLEPLAY_PROMPT
from app.tool import (
    DialogueHistory,
    Reflection,
    RelationTool,
    ScenarioReader,
    ScenarioWriter,
    ScheduleReader,
    ScheduleWriter,
    SendTelegramMessage,
    SpeakInPerson,
    Terminate,
    ToolCollection,
    WebSearch,
)


class AgentService:
    """Service for creating and managing agent instances"""
    
    @staticmethod
    def create_agent(
        session_id: str,
        name: str = "Stacy",
        roleplay_prompt: str = ROLEPLAY_PROMPT,
        character_id: Optional[str] = None,
        llm_settings: Optional[LLMSettings] = None,
        visible_for_characters: Optional[List[str]] = None,
    ) -> Character:
        """Create a new agent instance
        
        Args:
            session_id: Session ID (required)
            name: Agent name
            roleplay_prompt: Roleplay prompt
            character_id: Optional character ID
            llm_settings: Optional LLM settings
            visible_for_characters: Character IDs that can see messages
            
        Returns:
            Character agent instance
        """
        logger.info(f"Creating agent: {name} (character_id: {character_id}) for session: {session_id}")
        
        # Create LLM
        if llm_settings:
            llm = LLM(settings=llm_settings)
            logger.info(f"Using custom LLM settings: {llm_settings.model}")
        else:
            llm = LLM(config_name="openai")
            logger.info("Using default LLM config from config.toml")
        
        # Create agent with tools (id will be auto-generated by Runnable)
        agent = Character(
            session_id=session_id,
            name=name,
            description="",
            roleplay_prompt=roleplay_prompt,
            character_id=character_id,
            llm=llm,
            available_tools=ToolCollection(
                Reflection(),
                Terminate(),
                WebSearch(),
                SpeakInPerson(session_id=session_id),
                SendTelegramMessage(session_id=session_id),
                DialogueHistory(session_id=session_id, character_id=character_id),
                ScheduleReader(session_id=session_id, character_id=character_id),
                ScheduleWriter(session_id=session_id, character_id=character_id),
                ScenarioReader(session_id=session_id, character_id=character_id),
                ScenarioWriter(session_id=session_id, character_id=character_id),
                RelationTool(session_id=session_id, character_id=character_id),
            ),
            max_steps=10,
            visible_for_characters=visible_for_characters,
        )
        
        return agent
